### ISSUE TITLE
在使用Clash for window后无法联网

### ISSUE THREAD

**Issue by CheMingXiang** [Richasy/BiliBili-UWP#27]
PC ：win10专业版

使用代理工具clash for window魔法上网时，使用规则代理，该软件无法连接网络，希望加入网络设置选项 ：比如
1：不使用任何代理
2:   使用系统代理
3:   自定义配置代理端

**Comment by Richasy** [comment]
UWP无法实现

**Comment by CMingXiang** [comment]
谢谢回复

**Comment by CMingXiang** [comment]
https://blog.csdn.net/hhxy_wlzx/article/details/103518566
Win10中允许UWP应用走代理的操作方法，通过这个解决了该问题
