### ISSUE TITLE
平板模式UI问题

### ISSUE THREAD

**Issue by 1525249038** [Richasy/BiliBili-UWP#5]
为什么平板的UI中间很大一部分区域都标注成文字了，视频相关反倒是只有下面一行。。。

**Comment by Richasy** [comment]
平板UI是出于妥协的考虑，以尽可能降低信息密度和资源占用来兼容低配置设备。空白区域是预留出来放置播放器的地方

**Comment by 1525249038** [comment]
> 平板UI是出于妥协的考虑，以尽可能降低信息密度和资源占用来兼容低配置设备。空白区域是预留出来放置播放器的地方

我刚刚使用这款软件，播放之后只有封面，和声音这是咋回事

**Comment by Richasy** [comment]
请提供视频ID

**Comment by 1525249038** [comment]
> 请提供视频ID

找到问题了，是我开启了HEVC编码问题，还有就是我现在在使用桌面模式播放页面的进度条感觉太宽了直接占用了1/5
![image](https://user-images.githubusercontent.com/46812909/101233635-283df000-36f4-11eb-8793-fbf7afa5e97b.png)


这样一看太宽了，然后播放的窗口比较小了

**Comment by Richasy** [comment]
默认模式更侧重于预览，如果需要，请全屏或铺满应用观看

**Comment by 1525249038** [comment]
> 默认模式更侧重于预览，如果需要，请全屏或铺满应用观看

![image](https://user-images.githubusercontent.com/46812909/101233718-be721600-36f4-11eb-814c-be523976d112.png)

可是他有辣么宽

**Comment by Richasy** [comment]
播放窗口宽度由应用宽度决定，播放器控件肯定是跟着播放器宽度走而不是视频内容。

**Comment by 1525249038** [comment]
> 播放窗口宽度由应用宽度决定，播放器控件肯定是跟着播放器宽度走而不是视频内容。

我应该说高度，不是宽度，他有辣么高

**Comment by Richasy** [comment]
关于样式方面的问题……目前应用已经停止更新，除非遇到恶性BUG，否则不会再进行额外修改。

**Comment by 1525249038** [comment]
> 关于样式方面的问题……目前应用已经停止更新，除非遇到恶性BUG，否则不会再进行额外修改。

好的，打扰您了
