### ISSUE TITLE
能不能挂梯子打开啊？

### ISSUE THREAD

**Issue by LanGui777** [Richasy/BiliBili-UWP#7]
RT 挂了全局梯子后连不上了，w

**Comment by LanGui777** [comment]
![image](https://user-images.githubusercontent.com/52966445/102285181-af9b2700-3f70-11eb-8299-8eda71bc4c27.png)

**Comment by LanGui777** [comment]
https://zhuanlan.zhihu.com/p/29989157好吧，解决了

**Comment by LanGui777** [comment]
=。=然后第二个问题来了

**Comment by LanGui777** [comment]
![image](https://user-images.githubusercontent.com/52966445/102289442-a9f60f00-3f79-11eb-83d2-512409f5cabe.png)

**Comment by LanGui777** [comment]
![image](https://user-images.githubusercontent.com/52966445/102289504-d4e06300-3f79-11eb-9b6a-c8f6ddb5064a.png)

**Comment by zjyhjqs** [comment]
全局梯子哪怕网页版你也看不了. 要么自己设置PAC, 要么就分app代理. 

巨人最终季这个是港澳台区, 看不了正常. 这种灰色地带自己想办法, 别指望人.

**Comment by Richasy** [comment]
目前不会处理应用以外的事项
